### ISSUE TITLE
Infinite loop (or extreme slowness) in multiplication

### ISSUE THREAD

**Issue by darioizzo** [darioizzo/audi#1]
In the current state, the test trigonometry_perf does not finish on my machine.
In particular, when computing sine / cosine [here](https://github.com/darioizzo/audi/blob/master/tests/trigonometry_perf.cpp#L63) the program seems to stop.

Going inside the division operator series loop, it seems everything stops at [this line](https://github.com/darioizzo/audi/blob/master/src/gdual.hpp#L245) when i = 10, indicating a possible bug in the multiplication operator*= or an extreme slowness for that particular multiplication.

**Comment by bluescarni** [comment]
@darioizzo This seems to be fixed after the recent changes I pushed to Audi and to Piranha's development branch.

**Comment by darioizzo** [comment]
@bluescarni I can confirm that installing the newest audi and piranha (development branch) the issue is solved. 

I will close the ticket thanks! It is still interesting to keep in mind this particular test as it introduces [a division] (https://github.com/darioizzo/audi/blob/master/tests/trigonometry_perf.cpp#L63) that is particularly tough to make for audi. What makes the computation so difficult? A division of the same order and number of variables is tested in a different test [here] (https://github.com/darioizzo/audi/blob/master/tests/division_perf.cpp#L24) and takes 3-4 orders of magnitudes less to finish.

On my machine:
```bash
 ./division_perf 
Running 1 test case...
Testing division of (x1^2 + ... + xn^2) / (x1 * (x1 + x2 + .. + xn) ): 
Testing for order, n_vars: 10,	10
 0.011826s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)
```
vs.
```bash
./trigonometry_perf 
Running 1 test case...
Testing division of sin(1 + x1 + x2 + ...) / cos(1 + x1 + x2 + ...): 
Testing for order, n_vars: 10,	10
 26.986036s wall, 75.010000s user + 0.050000s system = 75.060000s CPU (278.1%)
```

**Comment by bluescarni** [comment]
@darioizzo With the next round of improvements in piranha the trigonometry test now takes ~7.5s on my machine.

**Comment by darioizzo** [comment]
I can confirm the improvement, here is the test before and after the latest piranha update on my osX machine at home:

before:
```bash
./trigonometry_perf
Running 1 test case...
Testing division of sin(1 + x1 + x2 + ...) / cos(1 + x1 + x2 + ...): 
Testing for order, n_vars: 10,	10
 11.370437s wall, 56.150000s user + 0.830000s system = 56.980000s CPU (501.1%)
```


after:
```bash
./trigonometry_perf
Running 1 test case...
Testing division of sin(1 + x1 + x2 + ...) / cos(1 + x1 + x2 + ...): 
Testing for order, n_vars: 10,	10
 8.992706s wall, 41.330000s user + 1.670000s system = 43.000000s CPU (478.2%)
```
