### ISSUE TITLE
Remove manual Python exposition of std::array

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#10]
Automatic conversion of ``std::array`` to/from Python was implemented here:

https://github.com/wjakob/pybind11/commit/10c74c6f34d5d4f08bd49309ffb6807f80684c98

We need to update our local snapshot of pybind11 and then remove the custom ``std::array`` handler.

**Comment by darioizzo** [comment]
Done

**Comment by bluescarni** [comment]
@darioizzo It was not really done, as the pybind11 snapshot was not updated. I did it in https://github.com/darioizzo/audi/commit/309d34e8efdc23ca0a047a4f7b04cee33e0b536b.

But we need to set up a CI system so that we cannot just pretend we fixed an issue :)
