### ISSUE TITLE
Potentially dangerous factorial computations

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#2]
Audi often uses this pattern in the computation of special functions of duals:

    double fact=1;
    [...]
    for (auto i = 2u; i <= d.get_order(); ++i) {
        factorial*=i * (i-1);
    }

This is potentially dangerous, as the expression ``i * (i-1)`` will be computed entirely with integral arithmetic (and it is thus susceptible to overflow). It would be better to rewrite the expression as ``i * (i-1.)``, for instance, so that all the computations are done in floating-point. Other alternatives are ``i * (double(i)-1)``, ``i * double(i-1)``, etc.

**Comment by darioizzo** [comment]
Ok, modified in commit 720924de811533385d0f5363f57c36f969fcff3a
