### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AlOa** [darioizzo/audi#22]
Hi,
I have a problem trying to compile a simple program using audi.
I have a compiler which does not fully support the c++14 standard, so I added the definitions of enable_if_t and  decay_t before include audi header. But when I try to instantiate a gdual (   audi::gdual<double> x(1.0,"x", 3) ) I get a strange compile error:

cannot call member function ‘decltype (((const audi::gdual<Cf>*)this)->audi::gdual<Cf>::m_p.find_cf(c)) audi::gdual<Cf>::get_derivative(const T&) const [with T = std::vector<double>; Cf = double; decltype (((const audi::gdual<Cf>*)this)->audi::gdual<Cf>::m_p.find_cf(c)) = double]’ without object
 , unsigned int> &dict) const -> decltype(get_derivative(std::vector<double>{}))

You  have any ideas why I get this error?
Thanks
                           Alberto

**Comment by darioizzo** [comment]
It could be the compiler you use not supporting an arguably valid c++11 syntax ..... we are thinking to downgrade the project to c++11, in which case we will test all those issues to. For the time being I am not sure how to help. Is it a big problem for you to update your compiler?

**Comment by AlOa** [comment]
Hi,
I'm using gcc4.8 and I can't, for now, updating it. Maybe I will try with
last clang which supports c++14.
Thanks!

                  Alberto

**Comment by darioizzo** [comment]
clang is tested with audi and works here. Let us know if it work for you

**Comment by darioizzo** [comment]
I have just downgraded the requirment to c++11. I tested on gcc6.1.1 and it compiles fine. Give it a try. Even if I am afraid your compiler does not support c++11 fully ..... let me know.

**Comment by AlOa** [comment]
With clang it works.
Thanks

                      Alberto

**Comment by darioizzo** [comment]
cool, let us know if you find audi useful and what do you use it for ...
