### ISSUE TITLE
pip install pyaudi 

### ISSUE THREAD

**Issue by delvillarfr** [darioizzo/audi#23]
I am running Ubuntu 16.04. `uname -m` returns `x86_64`.
I have python 2.7 installed and pip 9.0.1

`pip install pyaudi` returns the error message:
```
Could not find a version that satisfies the requirement pyaudi (from versions: )
No matching distribution found for pyaudi
```
I also downloaded the .whl file from [here](https://pypi.python.org/pypi/pyaudi), but 
`pip install pyaudi-1.0.3-cp27-cp27m-manylinux1_x86_64.whl` returns the error message:

```
pyaudi-1.0.3-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```

Is installation only possible through the instructions at: http://darioizzo.github.io/audi/installation.html ?

Thank you very much,
Francisco

**Comment by darioizzo** [comment]
The wheels are only available for some platforms. (OSx / python version). If yours is not supported you will need to compile and install.
