### ISSUE TITLE
Differences between audi and autograd

### ISSUE THREAD

**Issue by echo66** [darioizzo/audi#33]
Greetings!

I found out about this project after searching for new stuff on differential evolution. After reading the documentation, I was left wondering what is the practical differences between audi and autograd.

**Comment by darioizzo** [comment]
For gradients, I guess they offer the same capabilities, with autograd having the possibility to perform also backward differentiation. For higher order derivatives, pyaudi will handle them more efficiently. So if you need to build a high order Taylor map of your code go for pyaudi. If you need to compute only the gradient both will do, need t sure how they would compare in terms of efficiency, but my guess is that autograd might be faster as it's optimized for first order autodiff

**Comment by darioizzo** [comment]
Will close this for user inactivity.
