### ISSUE TITLE
Does it support multi-precision?

### ISSUE THREAD

**Issue by miaodi** [darioizzo/audi#35]
Since it depends on GMP. Can I use multi-precision data type in it?

Thanks

**Comment by darioizzo** [comment]
Yes, you can see a python tuorial at http://darioizzo.github.io/audi/notebooks/mp_gdual.html
or check the test code for c++ usage (https://github.com/darioizzo/audi/blob/master/tests/gdual_mp.cpp)

**Comment by darioizzo** [comment]
Will close this for user inactivity.....
