### ISSUE TITLE
Maximum order limit should be lowered

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#4]
The max truncation order, checked here,

https://github.com/darioizzo/audi/blob/master/src/gdual.hpp#L66

is the largest representable unsigned int ``M``. I think it should ``M - 1u`` instead, because there are quite a few loops like this one

https://github.com/darioizzo/audi/blob/master/src/functions.hpp#L297

which increase the counter by 2 (instead of 1) - these loops are thus not protected from possible overflows.

**Comment by darioizzo** [comment]
Ok, to allow future loop flexibility this is now changed to M-10u .... see commit (29490c0f4941e1dffaf85e4abcbeba8c91852b7e)
