### ISSUE TITLE
Add numpy accessor methods?

### ISSUE THREAD

**Issue by ianhbell** [darioizzo/audi#47]
I have learned that if you give a Python (or a wrapped C++) object a method called ``exp`` , then 

```python
o = Object() # could be a pyaudi.dual, or ....  (just pseudocode)
import numpy as np
print(np.exp(o)) 
```

would call the method ``o.exp()``.  This is very helpful because then existing code that is defined everywhere to call numpy methods works seamlessly with pyaudi.  As it is, to use ``pyaudi`` I would have to entirely rewrite my code to use ``pyaudi`` methods, and that is very inconvenient, and not possible in general.  This proposal would solve that problem.

**Comment by darioizzo** [comment]
In essence you suggest to have these functions  (starting from https://github.com/darioizzo/audi/blob/master/pyaudi/core.cpp#L29)  also exposed as methods of  a gdual (duplicated somewhere here: https://github.com/darioizzo/audi/blob/master/pyaudi/expose_gdual.hpp#L183) ...

Seems doable ... we are planning to rewrite the exposition in pybind11 at some point next year ... we could work on this then. 

You are also welcome to produce a PR in the current boost python setup ... in case you need this urgently....

**Comment by ianhbell** [comment]
I think you would just need to add the methods here: https://github.com/darioizzo/audi/blob/master/pyaudi/core.cpp#L191-L199

**Comment by darioizzo** [comment]
That would work only for the ``gdual_mp``, to get the same functionality across all ``gdual<T>`` some more would be need, but yes thats the gist ...

**Comment by darioizzo** [comment]
@ianhbell  #49 is addressing this and will be included in the next release (pybind11 made the code rather minimal)

**Comment by ianhbell** [comment]
Awesome! Sorry I didn't find the time to plug in and help out with this topic.

**Comment by darioizzo** [comment]
No worries, we had to move to pybind11 for the python binfings before adding this feature. Thanks for the report and good suggestion.
