### ISSUE TITLE
Exponentiation bug

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#5]
```c++
gdual x("x",3);
std::cout << pow(x,2.) << '\n';
std::cout << pow(x,2) << '\n';
std::cout << x*x << '\n';
```
This produces:

```
0
dx**2
dx**2
```

**Comment by darioizzo** [comment]
Preliminary investigation reveals this to be a fundamental issue on the algebraic formulas that are implemented for pow. In essence, f^a is written as (f0 + f - f0)^a = f0^a (1+ (f - f0) / f0 )^a. If f0 is the constant term of our Taylor representation of f, then this leads to the correct formula to evaluate the Taylor expansion of f^a. But when f0 = 0 we have 0 * inf type of problems .... the formula is not valid. Note that in the surroundings of 0 it still works nicely. Its only for the perfect 0 value that it fails.

I am investigating deeper into the theory to see how to fix this properly.

**Comment by darioizzo** [comment]
Ok. I have rearranged the terms in pow(gdual, double alpha) so that the Taylor coefficient are correctly computed as zeros or infs when alpha is not a positive integer. For the positive integer cases I have added a case.
