### ISSUE TITLE
Problem with the __pow__() operator (and others possibly) in the Python bindings

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#6]
It seems like pybind11 is not able to discriminate between ``__pow__`` being called with integer and double exponent. The double precision version is always called, I imagine because it is the first one being defined in the bindings.

This was a well-known quirky behaviour in Boost.Python that could be somewhat worked-around by carefully choosing the exposition order. It seems however that pybind11 always chooses the first exposed overload of the function if the arguments are convertible.

I imagine a similar problem exists for other operators/functions which have both an int and a double argument overload.

@darioizzo I think that for the arithmetic operators it's not a big deal to restrict ourselves only to interoperability with double precision, but what about the ``**`` operator? Is the exponentiation to double much worse than repeated multiplications?

**Comment by darioizzo** [comment]
It is. At the moment this is solved by the commit https://github.com/darioizzo/audi/commit/839b92bcb639387ee3698c5e04b116750dace1fe
detecting inside pow(gdual, double alpha) if alpha is a positive integer. In which case alpha*alpha*alpha*.... is computed ....

**Comment by bluescarni** [comment]
@darioizzo The int overload of ``pow()`` in the bindings should be removed then, and the operator overloads with respect to ``int`` as well IMO.
