### ISSUE TITLE
Dangerous old-style casts

### ISSUE THREAD

**Issue by bluescarni** [darioizzo/audi#8]
Example, the destructor of gdual:

```c++
~gdual() {assert(m_p.degree() <= (int)m_order);}
```

In ``get_derivative()``:

```c++
cumfact*=boost::math::factorial<double>((unsigned int)(*i));
```

Rather than silencing the compiler's protests, maybe we should look into fixing properly these :)

**Comment by darioizzo** [comment]
In ``get_derivative()``:
 I do not have
```c++
cumfact*=boost::math::factorial<double>((unsigned int)(*i));
```

only 

```c++
cumfact*=boost::math::factorial<double>(*i);
```

is this a planned commit?

**Comment by darioizzo** [comment]
Also, I do not see a plan on how we can fix this "properly" without changing arbitrarily the types decided for (example) m_order to match piranha API ... is that your suggestion?

**Comment by bluescarni** [comment]
My immediate suggestion for the dtor would be something like:

```c++
~gdual() {
    assert(m_p.degree() >= 0);
    assert(static_cast<unsigned>(m_p.degree()) <= m_order);
}
```

At least so we check first that the degree of the poly is always non-negative (which should always be the case, barring bugs?) and we don't risk out-of-range conversions when casting ``m_order`` instead.

More generally, doing these casts just to shut the compiler up seems like sweeping dust under the rug :)

**Comment by darioizzo** [comment]
Implemented as suggested
