### ISSUE TITLE
Python binding assumption on the library name does not hold necessarily in OSX homebrew

### ISSUE THREAD

**Issue by darioizzo** [darioizzo/audi#9]
In OSX (homebrew) the following symbolic links are often used to point to the currently active python library and headers:

```bash
/usr/local/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python
```

currently, the build system of audi python bindings, instead, make the assumption the library name contains also the python version, which is not true in case the user wants to use the above links.

Using the PyKEP style python management (https://github.com/esa/pykep/blob/master/cmake_scripts/find_python_library.py) would instead allow the python executable to take care finding all important information.

**Comment by bluescarni** [comment]
@darioizzo 

I think we ultimately need 2 or 3 different strategies to deal with this. The current system is works fine in linux/unix with the traditional ``PREFIX`` mechanism - which makes it easy to do local installations and which eventually will make distribution packaging straightforward (if we ever get there).

I have no idea about OSX packaging, as I don't own/use a mac. If you want to import the PyKEP scripts go ahead, but IMO those should apply only if one is building on OSX or possibly Windows.

(There's also to consider the fact that probably for Windows - and OSX also? I have no idea - we should probably aiming to have a Python wheel available, so that the user does not have to know anything about all this stuff)

**Comment by darioizzo** [comment]
The scripts in PyKEP work across platforms .... they let python itself deal with the mess as they use the module distutils, which is tasked to find the libraries and paths linked to some python executable.

An added advantage is that one can easily change python version by just changing the executable name.  The rest is updated automatically by python itself!!

**Comment by bluescarni** [comment]
In linux systems, one is not supposed to interfere with the system's package manager - which is exactly what you are doing when installing into the global modules dir (typically in ``/usr/lib/...``). And you will need to be root to do it as well, which is bad practice and a security risk.

**Comment by darioizzo** [comment]
The script would only locate the libraries to link to and the headers to use, it does not interfere with the install path.

**Comment by bluescarni** [comment]
Not sure I follow. For finding the Python library we use the standard CMake macros here:

https://github.com/darioizzo/audi/blob/python_bindings/cmake_modules/AudiPythonSetup.cmake

Is it not being found by CMake macros on OSX? If that's the case, then we should open a bug to CMake or investigate more in that direction. What we are doing above is some mumbo jumbo to determine the module install path, but the location of the Python library should be determined by CMake.

Also, in the PyKEP scripts I noticed that you are using ``get_config_vars()``, which has no guarantee of consistency across platforms:

https://docs.python.org/3/library/sysconfig.html

My current understanding is that there is no standard way to ask the Python interpreter where the Python library is.

**Comment by darioizzo** [comment]
CMake is in trouble whenever the OSX system python is bypassed by homebrew, fink, or macport package managers. I would not enter the mess of fixing this upstream as other projects have tried (https://github.com/Homebrew/homebrew/issues/25118) (https://cmake.org/Bug/view.php?id=14809) as, ultimately, I guess there is no clean solution.

The use of get_config_vars() is only limited to 
```python
py_lib_path = get_config_vars()["LIBDIR"]
```

which is returning a 'correct' value at least for the tested linux distros, windows, and osx.

**Comment by darioizzo** [comment]
Due to lack of agreement among developer I am closing this and just live with the consequences.
